apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
      app: das
  template:
    metadata:
      labels:
        tier: frontend
        app: das
    spec:
      containers:
      - name: frontend-cont
        image: gillrafay/das-frontend-img:1.0.0
        resources:
          requests:
            cpu: 1m
            memory: 50Mi
          limits:
            cpu: 10m
            memory: 200Mi
        env:
        - name: DOCTORS_SERVICE_URL
          value: doctor-backend:9090
        - name: APPOINTMENTS_SERVICE_URL
          value: appointment-backend:7070
        ports:
        - containerPort: 3000
          name: tcp

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    tier: frontend
    app: das
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 31000

