name: "workflow for the doctor microservice"

on:
  push:
    paths:
    - "doctors/**"
    #branches:
    #- "main"
    #- "master"

  pull_request:
    paths:
    - "./doctors/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      -
        name: Get the previous tag
        id: read_tag
        run: |
          export tag=$(grep "DOC_TAG=" .env | cut -d '=' -f2)
          echo "tag=$tag" >> $GITHUB_OUTPUT
      -
        name: Update the tag
        id: update_tag
        run: |
          wget -O /usr/local/bin/semver \
          https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
          chmod +x /usr/local/bin/semver
          new_tag=$(semver bump minor ${{ steps.read_tag.outputs.tag }})
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT
      -
        name: Update tag in the .env file
        run: |
          sed -i 's/DOC_TAG=.*/DOC_TAG=${{ steps.update_tag.outputs.new_tag }}/' .env
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .env
          git commit -m "Updated .env file. Auto-commit changes made by GitHub Actions workflow."
      - 
        name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./doctors/
          file: ./doctors/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/das-doctor-img:${{ steps.update_tag.outputs.new_tag }}
